import {defineField, defineType} from 'sanity'
import {orderRankField, orderRankOrdering} from '@sanity/orderable-document-list'
import {seoFields, seoGroup} from '../objects/seoFields'

/**
 * Industry document type - For industry-specific pages
 */

export default defineType({
  name: 'industry',
  title: 'Industry',
  type: 'document',
  icon: () => '🏢', // Building/office icon - better for industry pages
  initialValue: {
    isTemplate: false,
    sections: [

      // ── Hero — page heading, supporting text, CTA button, and image ────────
      {
        _type: 'columnsBlock',
        _key: 'section-hero',
        layout: '3/1',
        backgroundColor: 'none',
        backgroundGradient: 'none',
        paddingTop: '80px',
        paddingBottom: '80px',
        paddingLeft: '0px',
        paddingRight: '0px',
        paddingTopMobile: '48px',
        paddingBottomMobile: '48px',
        paddingLeftMobile: '0px',
        paddingRightMobile: '0px',
        column1PaddingBottomMobile: '32px',
        column2PaddingBottomMobile: '32px',
        column1: [
          {
            _type: 'headingComposition',
            _key: 'hero-heading',
            eyebrow: '[INDUSTRY] SOFTWARE',
            eyebrowType: 'h1',
            eyebrowStyle: 'red',
            title: 'Your headline here',
            text: [
              {
                _type: 'block',
                _key: 'hero-text',
                style: 'normal',
                markDefs: [],
                children: [
                  {
                    _type: 'span',
                    _key: 'hero-span',
                    text: 'Your supporting text here.',
                    marks: [],
                  },
                ],
              },
            ],
            theme: 'dark',
            textAlignment: 'LEFT',
            headingType: 'h2',
            displayType: 'h1',
            textType: 'lg',
            addBorderLine: false,
            experimentActive: false,
          },
          {
            _type: 'buttonStack',
            _key: 'hero-cta',
            buttonList: [
              {
                _key: 'btn-primary',
                buttonSettings: {
                  modalTrigger: false,
                  modalTriggerVideo: false,
                  btnLabel: 'Get started',
                  position: 'left',
                  buttonLink: {
                    href: 'https://sa-rolls.netlify.app/get-started',
                    openInNewTab: false,
                    noFollow: false,
                  },
                },
                btnIcon: {
                  iconFieldSvg: '',
                  iconPosition: 'left',
                },
                buttonStyles: {
                  bgKind: 'primary',
                },
              },
            ],
            styles: {
              layout: {
                spacing: {
                  marginTop: '0px',
                  marginBottom: '0px',
                  marginLeft: '0px',
                  marginRight: '0px',
                },
                alignment: 'LEFT',
              },
              animation: {
                type: 'none',
              },
            },
          },
        ],
        column2: [
          {
            _type: 'advancedImage',
            _key: 'hero-image',
            alt: 'Hero image',
          },
        ],
      },

      // ── Logo strip ────────────────────────────────────────────────────────
      {
        _type: 'columnsBlock',
        _key: 'section-logos',
        layout: '1',
        backgroundColor: 'none',
        backgroundGradient: 'none',
        paddingTop: '48px',
        paddingBottom: '56px',
        paddingLeft: '0px',
        paddingRight: '0px',
        paddingTopMobile: '32px',
        paddingBottomMobile: '48px',
        paddingLeftMobile: '0px',
        paddingRightMobile: '0px',
        column1PaddingBottomMobile: '32px',
        column2PaddingBottomMobile: '32px',
        column1: [
          {
            _type: 'logoSetReference',
            _key: 'logo-ref',
            reference: {
              _type: 'reference',
              _ref: 'logoSetGlobal',
            },
          },
        ],
      },
      // ── Business growth section heading with supporting text ──────────────
      {
        _type: 'columnsBlock',
        _key: 'section-business-growth',
        layout: '1',
        backgroundColor: 'var(--blue-99)',
        backgroundGradient: 'none',
        paddingTop: '56px',
        paddingBottom: '0px',
        paddingLeft: '0px',
        paddingRight: '0px',
        paddingTopMobile: '48px',
        paddingBottomMobile: '0px',
        paddingLeftMobile: '0px',
        paddingRightMobile: '0px',
        column1PaddingBottomMobile: '32px',
        column2PaddingBottomMobile: '32px',
        column1: [
          {
            _type: 'headingComposition',
            _key: 'business-growth-heading',
            eyebrow: 'Lorem ipsum',
            eyebrowType: 'div',
            eyebrowStyle: 'none',
            title: 'Grow your business with ROLLER',
            theme: 'dark',
            textAlignment: 'LEFT',
            headingType: 'h2',
            displayType: 'h2',
            textType: 'lg',
            addBorderLine: false,
            experimentActive: false,
            text: [
              {
                _type: 'block',
                _key: 'business-growth-text',
                style: 'normal',
                markDefs: [],
                children: [
                  { 
                    _type: 'span',
                    _key: 'business-growth-span',
                    text: "ROLLER is the global leader in trampoline park software - we've helped elevate the experience at over 700 trampoline parks around the world.",
                    marks: [],
                  },
                ],
              },
            ],
          },
        ],
      },
      // ── Customer testimonials — two quotes side by side ──────────────────
      {
        _type: 'columnsBlock',
        _key: 'section-quotes',
        layout: '2',
        backgroundColor: 'var(--blue-99)',
        backgroundGradient: 'none',
        paddingTop: '48px',
        paddingBottom: '0px',
        paddingLeft: '0px',
        paddingRight: '0px',
        paddingTopMobile: '32px',
        paddingBottomMobile: '0px',
        paddingLeftMobile: '0px',
        paddingRightMobile: '0px',
        column1PaddingBottomMobile: '32px',
        column2PaddingBottomMobile: '32px',
        column1: [
          {
            _type: 'quoteBlock',
            _key: 'quote-1',
            quoteText: 'Add your customer quote here.',
            quoteAuthor: 'Author Name',
            quoteTitle: 'Role, Company',
            customerStoryLink: {
              href: '/blog/',
              openInNewTab: false,
              noFollow: false,
            },
            linkLabel: 'Read the full story',
            imageType: 'logo',
            theme: 'dark',
            styleVariant: 'extrabold',
          },
        ],
        column2: [
          {
            _type: 'quoteBlock',
            _key: 'quote-2',
            quoteText: 'Add your customer quote here.',
            quoteAuthor: 'Author Name',
            quoteTitle: 'Role, Company',
            customerStoryLink: {
              href: '/blog/',
              openInNewTab: false,
              noFollow: false,
            },
            linkLabel: 'Read the full story',
            imageType: 'logo',
            theme: 'dark',
            styleVariant: 'extrabold',
          },
        ],
      },
      // ── User reviews widget (global reference) ───────────────────────────
      {
        _type: 'columnsBlock',
        _key: 'section-reviews',
        layout: '1',
        backgroundColor: 'var(--blue-99)',
        backgroundGradient: 'none',
        paddingTop: '80px',
        paddingBottom: '80px',
        paddingLeft: '0px',
        paddingRight: '0px',
        paddingTopMobile: '48px',
        paddingBottomMobile: '48px',
        paddingLeftMobile: '0px',
        paddingRightMobile: '0px',
        column1PaddingBottomMobile: '32px',
        column2PaddingBottomMobile: '32px',
        column1: [
          {
            _type: 'widgetUserReviewsReference',
            _key: 'reviews-ref',
            reference: {
              _type: 'reference',
              _ref: 'widgetUserReviews',
            },
          },
        ],
      },

      // ── Results list with section heading ────────────────────────────────
      {
        _type: 'columnsBlock',
        _key: 'section-heading-2',
        layout: '1',
        backgroundColor: 'var(--blue-95)',
        backgroundGradient: 'none',
        paddingTop: '80px',
        paddingBottom: '80px',
        paddingLeft: '0px',
        paddingRight: '0px',
        paddingTopMobile: '48px',
        paddingBottomMobile: '48px',
        paddingLeftMobile: '0px',
        paddingRightMobile: '0px',
        column1PaddingBottomMobile: '32px',
        column2PaddingBottomMobile: '32px',
        column1: [
          {
            _type: 'headingComposition',
            _key: 'heading-2-block',
            eyebrow: '',
            eyebrowType: 'div',
            eyebrowStyle: 'none',
            title: "Jumpstart your profits and elevate your trampoline park's guest experience",
            theme: 'dark',
            textAlignment: 'LEFT',
            headingType: 'h2',
            displayType: 'h2',
            textType: 'lg',
            addBorderLine: false,
            experimentActive: false,
          },
          {
            _type: 'resultsList',
            _key: 'results-list-block',
            theme: 'dark',
            useAnimations: false,
            items: [
              {
                _type: 'resultItem',
                _key: 'result-1',
                title: 'Maximize revenue with online bookings',
                content: 'Save your staff time and increase website conversions with our user-friendly online booking system. Guests can book everything from jump passes to party packages in a few clicks.',
                linkLabel: 'Explore online ticketing',
                link: {
                  href: 'https://sa-rolls.netlify.app/industries/trampoline-parks-software/ticketing-software/',
                  openInNewTab: false,
                  noFollow: false,
                },
                icon: '<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><path stroke="#085FF6" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M54.023 22.437H10.31m37.173-3.916v-4.574M16.85 18.523v-4.574m15.316 4.573v-4.574M43.77 50.375H12.242a1.932 1.932 0 0 1-1.932-1.932V18.137c0-1.067.865-1.933 1.932-1.933h39.85c1.066 0 1.931.866 1.931 1.933v21.805"></path><path stroke="#085FF6" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M19.963 31.084a2.61 2.61 0 1 1-5.222 0 2.61 2.61 0 0 1 5.222 0Zm9.876 0a2.61 2.61 0 1 1-5.222 0 2.61 2.61 0 0 1 5.222 0Zm19.752 0a2.61 2.61 0 1 1-5.221 0 2.61 2.61 0 0 1 5.221 0ZM19.963 41.729a2.61 2.61 0 1 1-5.222 0 2.61 2.61 0 0 1 5.222 0Zm9.876 0a2.61 2.61 0 1 1-5.222 0 2.61 2.61 0 0 1 5.222 0Zm9.876 0a2.61 2.61 0 1 1-5.221 0 2.61 2.61 0 0 1 5.221 0Zm0-10.645a2.61 2.61 0 1 0-5.221 0 2.61 2.61 0 0 0 5.221 0Zm10.477 11.712v7.272m3.636-3.636h-7.272m-3.879 0a7.515 7.515 0 1 1 15.03 0 7.515 7.515 0 0 1-15.03 0Z"></path></svg>',
              },
              {
                _type: 'resultItem',
                _key: 'result-2',
                title: 'Turn guests into loyal customers',
                content: 'Create an exceptional guest experience to stay ahead of the competition. With automatic capacity management and digital waivers, you can eliminate overbooking and avoid queues so guests can jump straight into the action.',
                linkLabel: 'Unlock better guest experiences',
                link: {
                  href: 'https://sa-rolls.netlify.app/get-started/',
                  openInNewTab: false,
                  noFollow: false,
                },
                icon: '<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><path stroke="#0960F6" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="1.786" d="M39.601 20.621v4.96a9.056 9.056 0 0 1-9.059 9.059h-.215a9.056 9.056 0 0 1-9.059-9.06v-4.436m12.959 36.158h-7.754c-2.779 0-3.147-2.042-8.844-2.487h-2.87a2.267 2.267 0 0 1-2.273-2.272v-4.668c0-6.433 5.22-11.638 11.638-11.638h1.336m0 0a4.686 4.686 0 0 0 4.683 4.606h.368a4.686 4.686 0 0 0 4.683-4.606m-9.734 0v-3.014m9.734 3.014H36.9c1.947 0 3.786.48 5.404 1.329m-7.109-1.33v-2.88"></path><path stroke="#0960F6" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="1.786" d="M39.601 21.097s.384-5.865-5.62-8.997c0 0-1.827 6.802-13.296 9.182 0 0-3.93-11.562.983-14.372.552-.307 1.458-.276 1.98.062.753.476 1.505 1.259 1.965 1.658.354.307.814.476 1.29.445a5.938 5.938 0 0 0 2.442-.69c4.564-1.88 11.114-1.611 11.285 4.636.092 3.93.368 7.186-1.029 8.076Z"></path><path stroke="#0960F6" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="m44.5 39 3.245 6.584L55 46.639l-5.25 5.125L50.99 59l-6.49-3.416L38.01 59l1.24-7.236L34 46.639l7.255-1.055L44.5 39Z"></path></svg>',
              },
              {
                _type: 'resultItem',
                _key: 'result-3',
                title: 'Saving busy operators precious time',
                content: 'Say goodbye to multiple, disjointed systems. ROLLER combines everything you need - from POS systems to membership management - in a single cloud-based platform. Plus, you can access it from anywhere.',
                linkLabel: 'Book a demo',
                link: {
                  href: 'https://sa-rolls.netlify.app/get-started/',
                  openInNewTab: false,
                  noFollow: false,
                },
                icon: '<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><path fill="#0960F6" fill-rule="evenodd" d="M23.896 8.902c0-.498.404-.902.902-.902H39.21c.498 0 .902.404.902.902v3.315a.902.902 0 0 1-.902.902h-3.317v2.819c3.4.682 6.658 2.267 9.395 4.754l1.301-1.316-1.011-1.023a.902.902 0 1 1 1.283-1.268l1.637 1.656.002.002 1.637 1.656a.902.902 0 0 1-1.284 1.269l-.996-1.008-1.289 1.304c7.266 7.888 7.116 20.258-.493 27.944a19.754 19.754 0 0 1-28.155 0c-7.763-7.856-7.763-20.606 0-28.461a19.733 19.733 0 0 1 10.169-5.507v-2.82h-3.29a.902.902 0 0 1-.903-.902V8.902Zm5.997 4.217v2.544a19.826 19.826 0 0 1 4.196-.002V13.12h-4.196Zm8.415-1.804v-1.51H25.7v1.51h12.608Zm-3.587 6.247a17.939 17.939 0 0 0-15.518 5.153c-7.068 7.153-7.068 18.772 0 25.925a17.95 17.95 0 0 0 25.589 0c7.08-7.152 7.069-18.771 0-25.925l-.034-.034a.916.916 0 0 1-.172-.17 17.924 17.924 0 0 0-9.608-4.908.902.902 0 0 1-.258-.041Zm-3.619 3.536v1.99a.902.902 0 0 0 1.804 0v-1.982a14.355 14.355 0 0 1 9.275 4.26 14.72 14.72 0 0 1 4.224 9.509h-1.954a.902.902 0 1 0 0 1.804h1.952a14.684 14.684 0 0 1-4.221 9.455 14.357 14.357 0 0 1-9.276 4.26v-2.38a.902.902 0 1 0-1.804 0v2.389a14.354 14.354 0 0 1-9.41-4.269 14.708 14.708 0 0 1-4.219-9.482h1.953a.902.902 0 1 0 0-1.804h-1.953a14.708 14.708 0 0 1 4.219-9.482 14.354 14.354 0 0 1 9.41-4.268Zm-15.46 14.657c-.001-4.22 1.588-8.44 4.767-11.657a16.153 16.153 0 0 1 11.618-4.828 16.153 16.153 0 0 1 11.438 4.828c6.354 6.432 6.367 16.871-.001 23.305a16.153 16.153 0 0 1-11.437 4.828h-.038a16.153 16.153 0 0 1-11.58-4.829c-3.177-3.215-4.766-7.43-4.767-11.647Z" clip-rule="evenodd"></path><path fill="#0960F6" fill-rule="evenodd" d="M32 27c.498 0 .902.404.902.902v5.105c1.175.392 2 1.527 2 2.826 0 1.612-1.27 2.971-2.902 2.971-1.631 0-2.902-1.36-2.902-2.97 0-1.3.825-2.435 2-2.827v-5.105c0-.498.404-.902.902-.902Zm0 7.666c-.578 0-1.098.494-1.098 1.167 0 .674.52 1.167 1.098 1.167.578 0 1.098-.493 1.098-1.167 0-.673-.52-1.167-1.098-1.167Z" clip-rule="evenodd"></path></svg>',
              },
              {
                _type: 'resultItem',
                _key: 'result-4',
                title: 'Efficiency at scale for multi-location venues',
                content: 'Use a centralized HQ account to manage all your locations. Set up products and user permissions across all parks simultaneously to reduce admin time and lock in your brand to maintain a consistent look and feel.',
                linkLabel: 'Discover HQ features',
                link: {
                  href: 'https://sa-rolls.netlify.app/features/multi-venue-management/',
                  openInNewTab: false,
                  noFollow: false,
                },
                icon: '<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><path stroke="#0960F6" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M38 32a6 6 0 1 1-12 0 6 6 0 0 1 12 0Z"></path><path stroke="#0960F6" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M43.936 31.97c0 6.61-5.359 11.97-11.97 11.97-6.61 0-11.97-5.36-11.97-11.97 0-6.611 5.36-11.97 11.97-11.97 6.611 0 11.97 5.359 11.97 11.97ZM31.967 13.963v5.967m0-5.967a3.318 3.318 0 1 0 0-6.636 3.318 3.318 0 0 0 0 6.636Zm15.707 8.952-5.167 2.983m9.7-1.769a3.318 3.318 0 1 1-3.318-5.747 3.318 3.318 0 0 1 3.318 5.747Zm-4.399 16.956-5.168-2.983m5.168 2.983a3.318 3.318 0 1 0 5.747 3.318 3.318 3.318 0 0 0-5.747-3.318Zm-15.841 8.952V44.07m0 5.967a3.318 3.318 0 1 0 0 6.636 3.318 3.318 0 0 0 0-6.636Zm-15.775-9.019 5.168-2.983m-5.168 2.983a3.318 3.318 0 1 0-5.747 3.318 3.318 3.318 0 0 0 5.747-3.318Zm.067-18.036 5.168 2.983m-6.383-7.516a3.318 3.318 0 1 1-3.318 5.747 3.318 3.318 0 0 1 3.318-5.747Z"></path></svg>',
              },
            ],
          },
        ],
      },
      // ── Secondary hero — heading, CTA, and image in equal columns ───────
      {
        _type: 'columnsBlock',
        _key: 'section-hero-b',
        layout: '2',
        backgroundColor: 'var(--blue-99)',
        backgroundGradient: 'none',
        paddingTop: '80px',
        paddingBottom: '80px',
        paddingLeft: '0px',
        paddingRight: '0px',
        paddingTopMobile: '48px',
        paddingBottomMobile: '48px',
        paddingLeftMobile: '0px',
        paddingRightMobile: '0px',
        column1PaddingBottomMobile: '32px',
        column2PaddingBottomMobile: '32px',
        column1: [
          {
            _type: 'headingComposition',
            _key: 'hero-b-heading',
            eyebrow: '[INDUSTRY] SOFTWARE',
            eyebrowType: 'h1',
            eyebrowStyle: 'red',
            title: 'Your headline here',
            text: [
              {
                _type: 'block',
                _key: 'hero-b-text',
                style: 'normal',
                markDefs: [],
                children: [
                  {
                    _type: 'span',
                    _key: 'hero-b-span',
                    text: 'Your supporting text here.',
                    marks: [],
                  },
                ],
              },
            ],
            theme: 'dark',
            textAlignment: 'LEFT',
            headingType: 'h2',
            displayType: 'h1',
            textType: 'lg',
            addBorderLine: false,
            experimentActive: false,
          },
          {
            _type: 'buttonStack',
            _key: 'hero-b-cta',
            buttonList: [
              {
                _key: 'hero-b-btn-primary',
                buttonSettings: {
                  modalTrigger: false,
                  modalTriggerVideo: false,
                  btnLabel: 'Get started',
                  position: 'left',
                  buttonLink: {
                    href: 'https://sa-rolls.netlify.app/get-started',
                    openInNewTab: false,
                    noFollow: false,
                  },
                },
                btnIcon: {
                  iconFieldSvg: '',
                  iconPosition: 'left',
                },
                buttonStyles: {
                  bgKind: 'primary',
                },
              },
            ],
            styles: {
              layout: {
                spacing: {
                  marginTop: '0px',
                  marginBottom: '0px',
                  marginLeft: '0px',
                  marginRight: '0px',
                },
                alignment: 'LEFT',
              },
              animation: {
                type: 'none',
              },
            },
          },
        ],
        column2: [
          {
            _type: 'advancedImage',
            _key: 'hero-b-image',
            alt: 'Hero image',
          },
        ],
      },
      // ── Comparison table with section heading ────────────────────────────
      {
        _type: 'columnsBlock',
        _key: 'section-heading-3',
        layout: '1',
        backgroundColor: 'var(--blue-95)',
        backgroundGradient: 'none',
        paddingTop: '80px',
        paddingBottom: '80px',
        paddingLeft: '0px',
        paddingRight: '0px',
        paddingTopMobile: '48px',
        paddingBottomMobile: '48px',
        paddingLeftMobile: '0px',
        paddingRightMobile: '0px',
        column1PaddingBottomMobile: '32px',
        column2PaddingBottomMobile: '32px',
        column1: [
          {
            _type: 'headingComposition',
            _key: 'heading-3-block',
            eyebrow: 'HOW WE COMPARE',
            eyebrowType: 'div',
            eyebrowStyle: 'red',
            title: 'The industry-leading platform for trampoline parks',
            text: [
              {
                _type: 'block',
                _key: 'heading-3-text',
                style: 'normal',
                markDefs: [],
                children: [
                  {
                    _type: 'span',
                    _key: 'heading-3-span',
                    text: "Make the switch to ROLLER's cutting-edge platform to increase online sales and reduce manual workflows.",
                    marks: [],
                  },
                ],
              },
            ],
            theme: 'dark',
            textAlignment: 'CENTER',
            headingType: 'h2',
            displayType: 'h2',
            textType: 'lg',
            addBorderLine: false,
            experimentActive: false,
          },
          {
            _type: 'comparisonTable',
            _key: 'comparison-table-block',
            columns: [
              {
                _type: 'comparisonColumn',
                _key: 'col-roller',
                title: "ROLLER's trampoline park software",
                isCompetitor: false,
                items: [
                  { _type: 'comparisonItem', _key: 'ci-1', text: 'Modern, cloud-based solution' },
                  { _type: 'comparisonItem', _key: 'ci-2', text: 'Robust system for growing venues' },
                  { _type: 'comparisonItem', _key: 'ci-3', text: 'The truly all-in-one platform' },
                  { _type: 'comparisonItem', _key: 'ci-4', text: 'Purpose-built for trampoline parks' },
                  { _type: 'comparisonItem', _key: 'ci-5', text: 'Digital solution that makes selling online easy' },
                ],
              },
              {
                _type: 'comparisonColumn',
                _key: 'col-other',
                title: 'Other software',
                isCompetitor: true,
                items: [
                  { _type: 'comparisonItem', _key: 'ci-6', text: 'Clunky, dated, server-based solution' },
                  { _type: 'comparisonItem', _key: 'ci-7', text: 'Entry-level solution with limited functionality' },
                  { _type: 'comparisonItem', _key: 'ci-8', text: 'Disjointed connection between systems' },
                  { _type: 'comparisonItem', _key: 'ci-9', text: 'Missing key functionality, like waivers' },
                  { _type: 'comparisonItem', _key: 'ci-10', text: 'Time-consuming with manual admin required' },
                ],
              },
            ],
          },
        ],
      },
      // ── Features stacked content — alternating image and text rows ─────────
      {
        _type: 'columnsBlock',
        _key: 'section-features-stacked',
        layout: '1',
        backgroundColor: 'none',
        backgroundGradient: 'none',
        paddingTop: '80px',
        paddingBottom: '80px',
        paddingLeft: '0px',
        paddingRight: '0px',
        paddingTopMobile: '48px',
        paddingBottomMobile: '48px',
        paddingLeftMobile: '0px',
        paddingRightMobile: '0px',
        column1PaddingBottomMobile: '32px',
        column2PaddingBottomMobile: '32px',
        column1: [
          {
            _type: 'featuresStackedContent',
            _key: 'features-stacked-block',
            theme: 'dark',
            textAlignment: 'LEFT',
            eyebrowType: 'div',
            eyebrowStyle: 'red',
            headingType: 'h3',
            displayType: 'h2',
            textType: 'lg',
            items: [
              {
                _type: 'featureItem',
                _key: 'feature-item-memberships',
                eyebrow: 'MEMBERSHIPS',
                title: 'Automated recurring revenue',
                text: "Make upsells easier and convert guests into regulars with intuitive membership sign-ups. Once you've made your sale online or at the POS, enjoy hands-off recurring revenue with automatic repeat billing.",
                imageAlt: 'Membership',
                imagePosition: 'left',
                imageRatio: 'aspect-square',
                showStats: false,
                showQuote: false,
                showCta: true,
                ctaText: 'Explore memberships',
                ctaLink: 'https://www.roller.software/features/membership-management-software/',
                ctaOpenInNewTab: false,
                ctaIconPosition: 'right',
                ctaKind: 'ghost',
              },
            ],
          },
        ],
      },
      // ── Features selector (global reference) ─────────────────────────────
      {
        _type: 'columnsBlock',
        _key: 'section-features-selector',
        layout: '1',
        backgroundColor: 'var(--blue-99)',
        backgroundGradient: 'none',
        paddingTop: '80px',
        paddingBottom: '80px',
        paddingLeft: '0px',
        paddingRight: '0px',
        paddingTopMobile: '48px',
        paddingBottomMobile: '48px',
        paddingLeftMobile: '0px',
        paddingRightMobile: '0px',
        column1PaddingBottomMobile: '32px',
        column2PaddingBottomMobile: '32px',
        column1: [
          {
            _type: 'featuresSelectorGlobalReference',
            _key: 'features-selector-ref',
            reference: {
              _type: 'reference',
              _ref: 'featuresSelectorGlobal',
            },
          },
        ],
      },
      // ── Frequently asked questions ────────────────────────────────────────
      {
        _type: 'columnsBlock',
        _key: 'section-faqs',
        layout: '1',
        backgroundColor: 'var(--blue-99)',
        backgroundGradient: 'none',
        paddingTop: '80px',
        paddingBottom: '80px',
        paddingLeft: '0px',
        paddingRight: '0px',
        paddingTopMobile: '48px',
        paddingBottomMobile: '48px',
        paddingLeftMobile: '0px',
        paddingRightMobile: '0px',
        column1PaddingBottomMobile: '32px',
        column2PaddingBottomMobile: '32px',
        column1: [
          {
            _type: 'faqs',
            _key: 'faqs-block',
            theme: 'light',
            expandFirst: false,
            heading: {
              eyebrow: 'NEED SOME HELP?',
              eyebrowType: 'div',
              eyebrowStyle: 'red',
              title: 'Frequently Asked Trampoline Park Software Questions',
              theme: 'dark',
              textAlignment: 'CENTER',
              headingType: 'h2',
              displayType: 'h2',
              textType: 'lg',
              addBorderLine: false,
              experimentActive: false,
            },
            items: [
              {
                _type: 'faqItem',
                _key: 'faq-1',
                title: 'What is trampoline park software, and what does it help operators do?',
                content: "Trampoline park software is a specialized tool that helps operators manage their facilities more efficiently. It offers features like booking management, waiver handling, point-of-sale transactions, attendance tracking, staff scheduling, inventory management, reporting, and more. This software enhances guest experiences, streamlines operations, and improves business success.",
              },
              {
                _type: 'faqItem',
                _key: 'faq-2',
                title: 'What should attractions business leaders look for in a trampoline park software solution?',
                content: "When choosing trampoline park software, attractions business leaders should look for: comprehensive features like online booking, waivers, POS, scheduling, and reporting, a user-friendly interface with customization options, and the ability to integrate with other tools and systems. Moreover, strong support, training, and security measures will ensure long-term success in managing your trampoline park.",
              },
              {
                _type: 'faqItem',
                _key: 'faq-3',
                title: 'What makes ROLLER different from other venue management tools?',
                content: "While many trampoline park software solutions may appear the same on paper, the way both operators and guests use them and the results they drive can be widely different. ROLLER offers a cloud-based, easy-to-use, all-in-one platform that helps operators grow and scale their businesses, driving real results. We focus on providing operators with data-driven insights seamlessly so they can make better-informed decisions, operate more efficiently and drive a better guest experience.",
              },
              {
                _type: 'faqItem',
                _key: 'faq-4',
                title: 'How can operators choose a scalable software solution for trampoline parks that can accommodate future growth?',
                content: "When selecting scalable software to accommodate future growth and ensure brand consistency across multiple locations, focus on solutions that manage and oversee all venues from a single platform. Cloud-based systems provide flexible scalability without requiring extensive hardware upgrades, while a strong vendor track record and success stories indicate a solution provider's capability to support expansion.",
              },
              {
                _type: 'faqItem',
                _key: 'faq-5',
                title: 'How does ROLLER help operators drive better guest experiences?',
                content: "ROLLER empowers operators to enhance guest experiences through its comprehensive venue management tools. With streamlined online booking and ticketing, guests can easily plan their visits, reducing wait times and enhancing convenience. The platform's user-friendly interface ensures smooth check-ins and purchases at point-of-sale, while integrated waiver management ensures a seamless and secure check-in process. ROLLER's data-driven insights enable operators to personalize offerings, optimize scheduling, and tailor marketing efforts to meet guest preferences. This holistic approach ultimately results in more enjoyable and memorable experiences, fostering guest loyalty and positive reviews.",
              },
            ],
          },
        ],
      },
      // ── Bottom CTA — heading and call-to-action button ───────────────────
      {
        _type: 'columnsBlock',
        _key: 'section-cta',
        layout: '4/1',
        backgroundColor: 'var(--blue-90)',
        backgroundGradient: 'none',
        paddingTop: '80px',
        paddingBottom: '80px',
        paddingLeft: '0px',
        paddingRight: '0px',
        paddingTopMobile: '48px',
        paddingBottomMobile: '48px',
        paddingLeftMobile: '0px',
        paddingRightMobile: '0px',
        column1PaddingBottomMobile: '32px',
        column2PaddingBottomMobile: '32px',
        column1: [
          {
            _type: 'headingComposition',
            _key: 'cta-heading',
            eyebrow: 'Lorem ipsum',
            eyebrowType: 'div',
            eyebrowStyle: 'none',
            title: 'Ready to get started?',
            text: [
              {
                _type: 'block',
                _key: 'cta-text',
                style: 'normal',
                markDefs: [],
                children: [
                  {
                    _type: 'span',
                    _key: 'cta-span',
                    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
                    marks: [],
                  },
                ],
              },
            ],
            theme: 'dark',
            textAlignment: 'LEFT',
            headingType: 'h2',
            displayType: 'h2',
            textType: 'lg',
            addBorderLine: false,
            experimentActive: false,
          },
        ],
        column2: [
          {
            _type: 'button',
            _key: 'cta-button',
          },
        ],
      },
    ],
  },
  orderings: [
    orderRankOrdering,
    {
      title: 'Templates First',
      name: 'templatesFirst',
      by: [
        // Sort by isTemplate descending: true values first (templates at top)
        // This should work regardless of draft/published status
        {field: 'isTemplate', direction: 'desc'},
        // Then by _id to ensure consistent ordering (published vs drafts)
        {field: '_id', direction: 'asc'},
        {field: 'title', direction: 'asc'},
      ],
    },
  ],
  groups: [
    {name: 'content', title: 'Content', default: true},
    {name: 'settings', title: 'Settings'},
    seoGroup,
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule) => Rule.required(),
      group: 'content',
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      validation: (Rule) => Rule.required(),
      options: {
        source: 'title',
        maxLength: 96,
      },
      group: 'content',
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'text',
      rows: 3,
      group: 'content',
    }),
    // Order rank for drag-and-drop ordering
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    orderRankField({type: 'industry', newItemPosition: 'before'}) as any,
    defineField({
      name: 'isTemplate',
      title: 'Is Template',
      type: 'boolean',
      description: 'Mark this industry page as a template. Templates will appear at the top of the industries list.',
      initialValue: false,
      group: 'settings',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'sections',
      title: 'Page Sections',
      type: 'array',
      group: 'content',
      of: [
        {
          type: 'columnsBlock',
        },
        {
          type: 'divider',
        },
      ],
    }),
    // Settings
    defineField({
      name: 'announcementBar',
      title: 'Announcement Bar',
      type: 'announcementBarSettings',
      group: 'settings',
    }),
    // SEO
    ...seoFields,
  ],
  preview: {
    select: {
      title: 'title',
      slug: 'slug.current',
      isTemplate: 'isTemplate',
    },
    prepare({title, slug, isTemplate}) {
      return {
        title: isTemplate ? `📋 ${title || 'Untitled Industry'} (Template)` : title || 'Untitled Industry',
        subtitle: `/industries/${slug}`,
      }
    },
  },
})
